In [105]:
import pandas as pd
import numpy as np
df=pd.read_csv("D:\Code\Python\Datasets\mtcars.csv")

In [106]:
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [107]:
df.tail()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [108]:
df.shape

(32, 12)

In [109]:
y=np.transpose(np.asmatrix(df['mpg']))
y.shape

(32, 1)

mpg=β0+β1.hp+β1.wt+β1.disp+ϵ

In [110]:
Intercept=pd.DataFrame(np.ones(y.shape))
Intercept.head()

0
0  1.0
1  1.0
2  1.0
3  1.0
4  1.0

In [111]:
Xdf0=df[['hp','wt','disp']]
Xdf0.head()

hp     wt   disp
0  110  2.620  160.0
1  110  2.875  160.0
2   93  2.320  108.0
3  110  3.215  258.0
4  175  3.440  360.0

In [112]:
Xdf1=pd.concat([Intercept,Xdf0],axis=1)
Xdf1.head()

0   hp     wt   disp
0  1.0  110  2.620  160.0
1  1.0  110  2.875  160.0
2  1.0   93  2.320  108.0
3  1.0  110  3.215  258.0
4  1.0  175  3.440  360.0

In [113]:
X=np.asmatrix(Xdf1)
X

matrix([[  1.   , 110.   ,   2.62 , 160.   ],
        [  1.   , 110.   ,   2.875, 160.   ],
        [  1.   ,  93.   ,   2.32 , 108.   ],
        [  1.   , 110.   ,   3.215, 258.   ],
        [  1.   , 175.   ,   3.44 , 360.   ],
        [  1.   , 105.   ,   3.46 , 225.   ],
        [  1.   , 245.   ,   3.57 , 360.   ],
        [  1.   ,  62.   ,   3.19 , 146.7  ],
        [  1.   ,  95.   ,   3.15 , 140.8  ],
        [  1.   , 123.   ,   3.44 , 167.6  ],
        [  1.   , 123.   ,   3.44 , 167.6  ],
        [  1.   , 180.   ,   4.07 , 275.8  ],
        [  1.   , 180.   ,   3.73 , 275.8  ],
        [  1.   , 180.   ,   3.78 , 275.8  ],
        [  1.   , 205.   ,   5.25 , 472.   ],
        [  1.   , 215.   ,   5.424, 460.   ],
        [  1.   , 230.   ,   5.345, 440.   ],
        [  1.   ,  66.   ,   2.2  ,  78.7  ],
        [  1.   ,  52.   ,   1.615,  75.7  ],
        [  1.   ,  65.   ,   1.835,  71.1  ],
        [  1.   ,  97.   ,   2.465, 120.1  ],
        [  1.   , 150.   ,   3.52 

In [114]:
Xt=X.T

In [115]:
X[:,:]

matrix([[  1.   , 110.   ,   2.62 , 160.   ],
        [  1.   , 110.   ,   2.875, 160.   ],
        [  1.   ,  93.   ,   2.32 , 108.   ],
        [  1.   , 110.   ,   3.215, 258.   ],
        [  1.   , 175.   ,   3.44 , 360.   ],
        [  1.   , 105.   ,   3.46 , 225.   ],
        [  1.   , 245.   ,   3.57 , 360.   ],
        [  1.   ,  62.   ,   3.19 , 146.7  ],
        [  1.   ,  95.   ,   3.15 , 140.8  ],
        [  1.   , 123.   ,   3.44 , 167.6  ],
        [  1.   , 123.   ,   3.44 , 167.6  ],
        [  1.   , 180.   ,   4.07 , 275.8  ],
        [  1.   , 180.   ,   3.73 , 275.8  ],
        [  1.   , 180.   ,   3.78 , 275.8  ],
        [  1.   , 205.   ,   5.25 , 472.   ],
        [  1.   , 215.   ,   5.424, 460.   ],
        [  1.   , 230.   ,   5.345, 440.   ],
        [  1.   ,  66.   ,   2.2  ,  78.7  ],
        [  1.   ,  52.   ,   1.615,  75.7  ],
        [  1.   ,  65.   ,   1.835,  71.1  ],
        [  1.   ,  97.   ,   2.465, 120.1  ],
        [  1.   , 150.   ,   3.52 

In [116]:
β=(np.linalg.inv(Xt*X))*Xt*y
β

matrix([[ 3.71055053e+01],
        [-3.11565508e-02],
        [-3.80089058e+00],
        [-9.37009081e-04]])

In [117]:
np.round(β,1)

array([[37.1],
       [-0. ],
       [-3.8],
       [-0. ]])

Using statsmodel package

In [118]:
import statsmodels.api as sm

In [119]:
model=sm.OLS(y,X).fit()

In [120]:
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.827
Model:                            OLS   Adj. R-squared:                  0.808
Method:                 Least Squares   F-statistic:                     44.57
Date:                Tue, 16 Apr 2024   Prob (F-statistic):           8.65e-11
Time:                        22:14:04   Log-Likelihood:                -74.321
No. Observations:                  32   AIC:                             156.6
Df Residuals:                      28   BIC:                             162.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         37.1055      2.111     17.579      0.0

Using sklearn

In [121]:
yf=np.ravel(y)

In [122]:
from sklearn.linear_model import LinearRegression
import numpy as np
# Create a LinearRegression object
reg = LinearRegression()
# Fit the model
reg.fit(Xdf0, yf)
# Print the coefficients
print('Coefficients:', reg.coef_)
print('Intercept:', reg.intercept_)


Coefficients: [-3.11565508e-02 -3.80089058e+00 -9.37009081e-04]
Intercept: 37.10550526903208
